--- 
- 
  gather_facts: false
  hosts: testeci
  name: "Deploy QA"
  become: true
  tasks: 
    - 
      file: "path=/bionexo state=directory"
      name: "Creates directory bionexo"
    - 
      copy: 
        dest: /bionexo/docker-compose.yml
        group: root
        mode: 420
        owner: root
        src: docker-compose.yml
    - 
      shell: "sudo docker-compose -f /bionexo/docker-compose.yml up -d"
